# working-directory: /data/d2s-workspace
dataset: drugbank



# d2s-download params
download-username: username
download-password: password

# tmp RDF4J server SPARQL endpoint to load generic RDF
#sparql-tmp-triplestore-url: http://graphdb:7200
#sparql-tmp-triplestore-url: http://node000002.cluster.ids.unimaas.nl/
sparql-tmp-triplestore-url: http://graphdb.dumontierlab.com/repositories/test-vincent
# sparql-tmp-triplestore-repository: "public"
# sparql-tmp-service-url: "repository:public"
sparql-tmp-service-url: "http://localhost:7200/repositories/test-vincent"
sparql-tmp-triplestore-username: import_user
sparql-tmp-triplestore-password: test

sparql-tmp-graph-uri: "https://w3id.org/data2services/graph/xml2rdf"

# Final RDF4J server SPARQL endpoint to load the BioLink RDF
#sparql-final-triplestore-url: http://graphdb:7200
# sparql-final-triplestore-url: http://node000002.cluster.ids.unimaas.nl/
sparql-final-triplestore-url: http://graphdb.dumontierlab.com/repositories/test-vincent/statements
sparql-final-triplestore-username: import_user
sparql-final-triplestore-password: test

sparql-final-graph-uri: https://w3id.org/data2services/graph/biolink/drugbank

sparql-transform-queries-path: https://github.com/MaastrichtU-IDS/d2s-transform-template/tree/master/datasets/drugbank/mappings/1
sparql-insert-metadata-path: https://github.com/MaastrichtU-IDS/d2s-transform-template/tree/master/datasets/drugbank/metadata/1

# Argo require to use the URL at the moment