
## Transform CSV

dataset_to_process: "cohd"

sparql_final_graph_uri: "https://w3id.org/trek/graph/cohd"

# Final RDF4J server SPARQL endpoint to load the BioLink RDF
# sparql_final_triplestore_url: "http://graphdb:7200/repositories/trek/statements"
sparql_final_triplestore_url: "http://graphdb:7200/repositories/trek/statements"
# sparql_final_triplestore_url: "http://virtuoso:8890/sparql"

final_graphdb_url: "http://localhost:7200"
tmp_graphdb_repository: "test"
final_graphdb_repository: "trek"

sparql_tmp_service_url: "http://localhost:7200/repositories/test"
# sparql_tmp_service_url: "http://virtuoso:8890/sparql"
# sparql_tmp_service_url: "http://localhost:8890/sparql"

sparql_final_triplestore_username: "admin"
sparql_final_triplestore_password: "root"
# sparql_final_triplestore_username: "import_user"
# sparql_final_triplestore_password: "password"

# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"

# tmp RDF4J server SPARQL endpoint to load generic RDF
sparql_tmp_triplestore_url: "http://virtuoso:8890/sparql"
sparql_tmp_triplestore_username: "dba"
sparql_tmp_triplestore_password: "dba"

sparql_tmp_graph_uri: "https://w3id.org/d2s/graph/autor2rml"
# sparql_tmp_graph_uri: "https://w3id.org/d2s/graph/autor2rml/cohd"
# sparql_tmp_graph_uri: "https://w3id.org/d2s/graph/autor2rml"

# tmp_triplestore_container_id: "d2s-virtuoso"
# tmp_triplestore_load_dir: "/usr/local/virtuoso-opensource/var/lib/virtuoso/db"
tmp_triplestore_container_id: "d2s-graphdb"
tmp_triplestore_load_dir: "/root/graphdb-import"


# Split params
# split_property: "https://w3id.org/biolink/vocab/has_participant"
# split_class: "https://w3id.org/biolink/vocab/GeneGrouping"
# split_delimiter: ","
# split_quote: '"'

sparql_transform_queries_path: "mapping"
sparql_insert_metadata_path: "metadata"

# TODO: use workflows/csv-virtuoso.cwl ?
cwl_workflow_filename: "csv-graphdb.cwl"

config_dir:
  class: Directory
  path: .

cwl_dir:
  class: Directory
  path: ../../d2s-core/cwl