
dataset_to_process: "geonames"

## For XML workflows
# dir_to_process:
#   class: Directory
#   path: ../../workspace/input/geonames

sparql_final_graph_uri: "https://w3id.org/d2s/graph/geonames"

# Final RDF4J server SPARQL endpoint to load the generated RDF
sparql_final_triplestore_url: "http://graphdb:7200/repositories/geoeconomics/statements"
#sparql_final_triplestore_url: "https://graphdb.dumontierlab.com/repositories/geoeconomics/statements"

sparql_final_triplestore_username: "dba"
sparql_final_triplestore_password: "dba"



### Additional parameters for CWL workflows:

# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"

# tmp RDF4J server SPARQL endpoint to load generic RDF
sparql_tmp_triplestore_url: "http://virtuoso:8890/sparql"
# sparql_tmp_triplestore_url: "http://blazegraph:8082/bigdata/sparql"
sparql_tmp_service_url: "http://virtuoso:8890/sparql"
# sparql_tmp_service_url: "http://blazegraph:8082/bigdata/sparql"
sparql_tmp_triplestore_username: "dba"
sparql_tmp_triplestore_password: "dba"

sparql_tmp_graph_uri: "https://w3id.org/d2s/graph/autor2rml"
# sparql_tmp_graph_uri: "https://w3id.org/d2s/graph/xml2rdf"
tmp_triplestore_container_id: "d2s-virtuoso"
tmp_triplestore_load_dir: "/usr/local/virtuoso-opensource/var/lib/virtuoso/db"


# Split params
# split_property: "https://w3id.org/biolink/vocab/has_participant"
# split_class: "https://w3id.org/biolink/vocab/GeneGrouping"
# split_delimiter: ","
# split_quote: '"'

sparql_transform_queries_path: "mapping"
sparql_insert_metadata_path: "metadata"

cwl_workflow_filename: "virtuoso.cwl"

config_dir:
  class: Directory
  path: .

cwl_dir:
  class: Directory
  path: ../../d2s-core/cwl